### ISSUE TITLE
OpenBSD: test-oom: AttributeError: 'module' object has no attribute 'RLIMIT_AS'

### ISSUE THREAD

**Issue by jwilk** [jwilk/pdf2djvu#125]
The OOM test fails on OpenBSD:
```
======================================================================
ERROR: test-oom.test.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jwilk/pdf2djvu-0.9.7/tests/test-oom.py", line 54, in test
    with vm_limit(1 << 30):  # 1 GiB virtual memory limit
  File "/usr/local/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/jwilk/pdf2djvu-0.9.7/tests/test-oom.py", line 29, in vm_limit
    [lim_soft, lim_hard] = resource.getrlimit(resource.RLIMIT_AS)
AttributeError: 'module' object has no attribute 'RLIMIT_AS'
```

OpenBSD doesn't have `RLIMIT_AS`.
I guess we could use `RLIMIT_DATA` instead.

**Comment by jwilk** [comment]
Fixed in [0.9.8](https://groups.io/g/pdf2djvu/message/85).
